//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreriaDominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        public int Id { get; set; }
        public string titulo { get; set; }
        public Nullable<decimal> precio { get; set; }
    }
}
